console.log("process architecture = "+process.arch)
console.log("process id = "+process.pid)
console.log("process environment = "+ process.env)
console.log("process platform = "+process.platform)
console.log("process metadata = "+process.release)
console.log("process node version = "+process.version)
console.log("node dependencies version = "+process.versions)
console.log(process.cwd)